fix bug #6: TypeError: undefined is not a function
Bug arised due to missing semicolon in src/config/logging.js.
Prevent future bugs of this kind by changing the config file format
to coffeescript.